name: remote_config_generator
description: "a generator for remote config"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  code_builder: ^4.10.1
  dart_style: ^2.3.3
  flutter:
    sdk: flutter
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: